### ISSUE TITLE
[Request] Add PedalSubMenu isOpen?

### ISSUE THREAD

**Issue by MintLily** [gompocp/ActionMenuApi#6]
For a few niche things, I am trying to detect if my subMenu is currently open. There is no real easy way to handle this myself. I was wondering if it's possible to add a simple boolean to check if the menu is currently open.

Example:
```cs
public PedalSubMenu subMenu;
...
if (subMenu.isOpen) DoThings();
```

**Comment by gompoc** [comment]
Yep I can do that. There's a few things I'm currently fixing up too (including being able to use the two menus in vr at the same time) so I can add that to it as well. Also as an aside note the repo is now at `https://github.com/gompoc/VRChatMods/tree/master/ActionMenuApi` because I got locked out of this one)

**Comment by MintLily** [comment]
Ah okii, thankies~
